name: Build pull request.
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup jdk
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 15
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run build
        run: ./gradlew clean build
      - name: Run tests
        run: ./gradlew test